name: Raspberry Pi 3

on:
  pull_request:
    branches:
      - "main"
      - "master"
  pull_request_target:
    branches:
      - "main"
      - "master"

  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?*
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+

  workflow_dispatch:

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@2bb54e7c3c715176446a895ed765346c52d480b2
    # prevent duplicate workflow executions for pull_request and pull_request_target
    if: |
      (
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event_name != 'pull_request_target'
      ) || (
        github.event.pull_request.head.repo.full_name != github.repository &&
        github.event_name == 'pull_request_target'
      )
    secrets: inherit
    with:
      machine: raspberrypi3
      test-environment: bm.balena-dev.com
      environment: balena-staging.com
